import 'package:flutter/material.dart';

class SecondTheme {
  final ThemeData myTheme = ThemeData(
    brightness: Brightness.light,
    primaryColor: const Color(0xff04575a),
    primaryColorLight: const Color(0xffcefbfd),
    primaryColorDark: const Color(0xff078e92),
    canvasColor: const Color(0xfffafafa),
    scaffoldBackgroundColor: const Color(0xfffafafa),
    bottomAppBarColor: const Color(0xffffffff),
    cardColor: const Color(0xff04575a),
    dividerColor: const Color(0x1f000000),
    highlightColor: const Color(0x66bcbcbc),
    splashColor: const Color(0x66c8c8c8),
    selectedRowColor: const Color(0xfff5f5f5),
    unselectedWidgetColor: const Color(0x8a000000),
    disabledColor: const Color(0x61000000),
    toggleableActiveColor: const Color(0xff09bdc3),
    secondaryHeaderColor: const Color(0xffe7fdfe),
    backgroundColor: const Color(0xff9df7fb),
    dialogBackgroundColor: const Color(0xffffffff),
    indicatorColor: const Color(0xff0becf4),
    hintColor: const Color(0x8a000000),
    errorColor: const Color(0xffd32f2f),
    buttonTheme: const ButtonThemeData(
      textTheme: ButtonTextTheme.normal,
      minWidth: 88,
      height: 36,
      padding: EdgeInsets.only(top: 0, bottom: 0, left: 16, right: 16),
      shape: RoundedRectangleBorder(
        side: BorderSide(
          color: Color(0xff000000),
          width: 0,
          style: BorderStyle.none,
        ),
        borderRadius: BorderRadius.all(Radius.circular(2.0)),
      ),
      alignedDropdown: false,
      buttonColor: Color(0xffe0e0e0),
      disabledColor: Color(0x61000000),
      highlightColor: Color(0x29000000),
      splashColor: Color(0x1f000000),
      focusColor: Color(0x1f000000),
      hoverColor: Color(0x0a000000),
      colorScheme: ColorScheme(
        primary: Color(0xff04575a),
        secondary: Color(0xff0becf4),
        surface: Color(0xffffffff),
        background: Color(0xff9df7fb),
        error: Color(0xffd32f2f),
        onPrimary: Color(0xffffffff),
        onSecondary: Color(0xff000000),
        onSurface: Color(0xff000000),
        onBackground: Color(0xffffffff),
        onError: Color(0xffffffff),
        brightness: Brightness.light,
      ),
    ),
    textTheme: const TextTheme(
      //   display4: TextStyle(
      //   color: Color( 0x8a000000 ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   display3: TextStyle(
      //   color: Color( 0x8a000000 ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   display2: TextStyle(
      //   color: Color( 0x8a000000 ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   display1: TextStyle(
      //   color: Color( 0x8a000000 ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   headline: TextStyle(
      //   color: Color( 0xdd000000 ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   title: TextStyle(
      //   color: Color( 0xdd000000 ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   subhead: TextStyle(
      //   color: Color( 0xdd000000 ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   body2: TextStyle(
      //   color: Color( 0xdd000000 ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   body1: TextStyle(
      //   color: Color( 0xdd000000 ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      caption: TextStyle(
        color: Color(0x8a000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      button: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      //   subtitle: TextStyle(
      //   color: Color( 0xff000000 ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      overline: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
    ),
    primaryTextTheme: const TextTheme(
      //   display4: TextStyle(
      //   color: Color( 0xb3ffffff ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   display3: TextStyle(
      //   color: Color( 0xb3ffffff ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   display2: TextStyle(
      //   color: Color( 0xb3ffffff ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   display1: TextStyle(
      //   color: Color( 0xb3ffffff ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   headline: TextStyle(
      //   color: Color( 0xffffffff ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   title: TextStyle(
      //   color: Color( 0xffffffff ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   subhead: TextStyle(
      //   color: Color( 0xffffffff ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   body2: TextStyle(
      //   color: Color( 0xffffffff ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      //   body1: TextStyle(
      //   color: Color( 0xffffffff ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      caption: TextStyle(
        color: Color(0xb3ffffff),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      button: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      //   subtitle: TextStyle(
      //   color: Color( 0xffffffff ),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      overline: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
    ),
    inputDecorationTheme: const InputDecorationTheme(
      labelStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      helperStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      hintStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      errorStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      errorMaxLines: null,
      // hasFloatingPlaceholder: true,
      isDense: false,
      // contentPadding: EdgeInsets.only(top: 12, bottom: 12, left: 0, right: 0),
      isCollapsed: false,
      prefixStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      suffixStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      counterStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      filled: false,
      fillColor: Color(0x00000000),
      errorBorder: OutlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000),
          width: 1,
          style: BorderStyle.solid,
        ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      focusedBorder: OutlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000),
          width: 1,
          style: BorderStyle.solid,
        ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      focusedErrorBorder: OutlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000),
          width: 1,
          style: BorderStyle.solid,
        ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      disabledBorder: OutlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000),
          width: 1,
          style: BorderStyle.solid,
        ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      enabledBorder: OutlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000),
          width: 1,
          style: BorderStyle.solid,
        ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      border: OutlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000),
          width: 1,
          style: BorderStyle.solid,
        ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
    ),
    iconTheme: const IconThemeData(
      color: Color(0xdd000000),
      opacity: 1,
      size: 24,
    ),
    primaryIconTheme: const IconThemeData(
      color: Color(0xffffffff),
      opacity: 1,
      size: 24,
    ),
    sliderTheme: const SliderThemeData(
      activeTrackColor: null,
      inactiveTrackColor: null,
      disabledActiveTrackColor: null,
      disabledInactiveTrackColor: null,
      activeTickMarkColor: null,
      inactiveTickMarkColor: null,
      disabledActiveTickMarkColor: null,
      disabledInactiveTickMarkColor: null,
      thumbColor: null,
      disabledThumbColor: null,
      thumbShape: null,
      overlayColor: null,
      valueIndicatorColor: null,
      valueIndicatorShape: null,
      showValueIndicator: null,
      valueIndicatorTextStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
    ),
    tabBarTheme: const TabBarTheme(
      indicatorSize: TabBarIndicatorSize.tab,
      labelColor: Color(0xffffffff),
      unselectedLabelColor: Color(0xb2ffffff),
    ),
    chipTheme: const ChipThemeData(
      backgroundColor: Color(0x1f000000),
      brightness: Brightness.light,
      deleteIconColor: Color(0xde000000),
      disabledColor: Color(0x0c000000),
      labelPadding: EdgeInsets.only(top: 0, bottom: 0, left: 8, right: 8),
      labelStyle: TextStyle(
        color: Color(0xde000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      padding: EdgeInsets.only(top: 4, bottom: 4, left: 4, right: 4),
      secondaryLabelStyle: TextStyle(
        color: Color(0x3d000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      secondarySelectedColor: Color(0x3d04575a),
      selectedColor: Color(0x3d000000),
      shape: StadiumBorder(
          side: BorderSide(
        color: Color(0xff000000),
        width: 0,
        style: BorderStyle.none,
      )),
    ),
    dialogTheme: const DialogTheme(
        shape: RoundedRectangleBorder(
      side: BorderSide(
        color: Color(0xff000000),
        width: 0,
        style: BorderStyle.none,
      ),
      borderRadius: BorderRadius.all(Radius.circular(0.0)),
    )),
    colorScheme: ColorScheme.fromSwatch(
        primarySwatch: const MaterialColor(4278474586, {
      50: Color(0xffe7fdfe),
      100: Color(0xffcefbfd),
      200: Color(0xff9df7fb),
      300: Color(0xff6df4f8),
      400: Color(0xff3cf0f6),
      500: Color(0xff0becf4),
      600: Color(0xff09bdc3),
      700: Color(0xff078e92),
      800: Color(0xff045e62),
      900: Color(0xff022f31)
    })).copyWith(secondary: const Color(0xff0becf4)),
    textSelectionTheme: const TextSelectionThemeData(
      cursorColor: Color(0xff4285f4),
      selectionColor: Color(0xff9df7fb),
      selectionHandleColor: Color(0xff6df4f8),
    ),
  );
}
